### ISSUE TITLE
Redux

### ISSUE THREAD

**Issue by HelenHMaher** [HelenHMaher/my-daily-climb#4]
create a redux framework for state management

**Comment by gooseNjuice** [comment]
Can I try to do it?

**Comment by HelenHMaher** [comment]
Thanks, @gooseNjuice!  It was cool to see your pull request come through.  I haven't worked with Redux much but everything looked good so far as I could tell :)

**Comment by gooseNjuice** [comment]
@HelenHMaher you're welcome :)
